name: Issue Closed Workflow

env:
  token: ${{ secrets.ACCESS_TOKEN }}

on:
  issues:
    types:
      - closed

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    container:
      image: node:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          always-auth: # optional, default is false
          node-version: # optional
          node-version-file: # optional
          architecture: # optional
          check-latest: # optional
          registry-url: # optional
          scope: # optional
          token: # optional, default is ${{ github.token }}
          cache: # optional
          cache-dependency-path: # optional
          version: # optional (deprecated)

      - name: Create src directory
        run: mkdir src

      - name: Run read_comment.sh
        run: |
          chmod +x ./read_comment.sh
          ./read_comment.sh
        shell: bash

      - name: Run upd_req2updates.sh
        run: |
          chmod +x ./upd_req2updates.sh
          ./upd_req2updates.sh
        shell: bash

      - name: Run dependency_updates.sh
        run: |
          chmod +x ./dependency_updates.sh
          ./dependency_updates.sh
        shell: bash
