env:
  token: ${{ secrets.ACCESS_TOKEN }}

name: create-map

on:
  issues:
    types:
      - closed

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Read comments
        run: |
          echo "Running read_comment.sh"
          chmod +x ./read_comment.sh
          ./read_comment.sh
        shell: bash

      - name: Create dependencies file
        run: |
          echo "Running package2dependency.sh"
          chmod +x ./upd_req2updates.sh
          ./upd_req2updates.sh
        shell: bash

      - name: Update the dependencies
        run: |
          echo "Running dependency_updates.sh"
          chmod +x ./dependency_updates.sh
          ./dependency_updates.sh
        shell: bash
