env:
  token: ${{ secrets.ACCESS_TOKEN }}

name: create-map
on:
  issues:
    types:
      - closed
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
        chmod +x ./read_comment.sh
        ./read_comment.sh
        chmod +x ./upd_req2updates.sh
        ./upd_req2updates.sh
        chmod +x ./dependency_updates.sh
        ./dependency_updates.sh
