env:
  token: ${{ secrets.ACCESS_TOKEN }}

name: create-map

on:
  issues:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Read comment
        run: |
          echo "Running read_comment.sh"
          chmod +x ./read_comment.sh
          ./read_comment.sh "${{ env.token }}"
        shell: bash
