env:
  token: ${{ secrets.ACCESS_TOKEN }}

name: create-map
on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
        chmod +x ./package2dependency.sh
        ./package2dependency.sh
        chmod +x ./check_latest.sh
        ./check_latest.sh
      shell: bash  
    - name: create issue
      run: |
        chmod +x ./Create_Issue.sh
        ./Create_Issue.sh
      shell: bash
