env:
  token: ${{ secrets.ACCESS_TOKEN }}

name: create-map
on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.email "prakhar.manitripathi.cd.mec20@itbhu.ac.in"
        git config --global user.name "codeprakhar"
      shell: bash
    - name: Run script file
      run: |
        chmod +x ./package2dependency.sh
        ./package2dependency.sh
        chmod +x ./check_latest.sh
        ./check_latest.sh
        chmod +x ./Create_Issue.sh
        ./Create_Issue.sh
      shell: bash